tensor   -> 원핫 백터를 이용해서 숫자로 변경
t -> e
e -> n
n -> s
s -> o
o -> r

x : tenso
y : ensor



In [9]:
import tensorflow.keras as keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

In [5]:
x = [[1, 0, 0, 0, 0, 0],    # t
     [0, 1, 0, 0, 0, 0],    # e
     [0, 0, 1, 0, 0, 0],    # n
     [0, 0, 0, 1, 0, 0],    # s
     [0, 0, 0, 0, 1, 0],]   # o

y = [[0, 1, 0, 0, 0, 0],    # e
     [0, 0, 1, 0, 0, 0],    # n
     [0, 0, 0, 1, 0, 0],    # s
     [0, 0, 0, 0, 1, 0],    # o
     [0, 0, 0, 0, 1, 1],]   # r

### 퀴즈
### 위 데이터에 대해 동작하는 모델을 만드세요

In [7]:
# 원 핫 백터이니까 categorical_crossentropy
# 모델 생성

# 모델 인스턴스화
model = Sequential()

# 입력 레이어 생성
model.add(Dense(units=512, activation='relu', input_shape=(784,)))

# 숨겨진 레이어 생성
model.add(Dense(units= 512, activation='relu'))

# 출력 레이어 생성
# softmax : 각 레이어의 값이 0에서 1 사이의 확률이 되도록 하고 레이어의 모든 출력이 1에 추가되로록 하는 활성 함수
model.add(Dense(units = 10, activation='softmax' ))

#  모델 요약
print(model.summary())

# 모델 컴파일
# 트레이닝 중 모델에서 성능을 파악하는 데 사용되는 손실 함수를 지정
# 트레이닝 동안 accury도 추적하도록 지정
model.compile(loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(x, y, epochs=10, verbose=2)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_4 (Dense)              (None, 512)               262656    
_________________________________________________________________
dense_5 (Dense)              (None, 10)                5130      
Total params: 669,706
Trainable params: 669,706
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/10


ValueError: in user code:

    C:\Users\Harmony05\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\keras\engine\training.py:855 train_function  *
        return step_function(self, iterator)
    C:\Users\Harmony05\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\keras\engine\training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Harmony05\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Harmony05\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Harmony05\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Harmony05\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\keras\engine\training.py:838 run_step  **
        outputs = model.train_step(data)
    C:\Users\Harmony05\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\keras\engine\training.py:795 train_step
        y_pred = self(x, training=True)
    C:\Users\Harmony05\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:1013 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    C:\Users\Harmony05\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:251 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer sequential_1 is incompatible with the layer: expected axis -1 of input shape to have value 784 but received input with shape (None, 6)


강사님 코드


In [8]:
model = keras.Sequential([keras.layers.Input(shape=(6,)),
                          keras.layers.Dense(6, activation='softmax')])

model.compile(optimizer=keras.optimizers.Adam(0.1),
              loss=keras.losses.categorical_crossentropy,
              metrics='acc')

model.fit(x, y, epochs=10, verbose=2)


Epoch 1/10
1/1 - 0s - loss: 2.1626 - acc: 0.4000
Epoch 2/10
1/1 - 0s - loss: 1.9331 - acc: 0.4000
Epoch 3/10
1/1 - 0s - loss: 1.7290 - acc: 0.6000
Epoch 4/10
1/1 - 0s - loss: 1.5445 - acc: 0.6000
Epoch 5/10
1/1 - 0s - loss: 1.3786 - acc: 0.6000
Epoch 6/10
1/1 - 0s - loss: 1.2305 - acc: 0.8000
Epoch 7/10
1/1 - 0s - loss: 1.0993 - acc: 0.8000
Epoch 8/10
1/1 - 0s - loss: 0.9839 - acc: 0.8000
Epoch 9/10
1/1 - 0s - loss: 0.8831 - acc: 0.8000
Epoch 10/10
1/1 - 0s - loss: 0.7959 - acc: 0.8000


### 퀴즈
### onehot vector 를 sparse 버전으로 변환

In [12]:
import numpy as np
from tensorflow import keras

def rnn_char_1_sparse():
    x = [[1, 0, 0, 0, 0, 0],    # t
         [0, 1, 0, 0, 0, 0],    # e
         [0, 0, 1, 0, 0, 0],    # n
         [0, 0, 0, 1, 0, 0],    # s
         [0, 0, 0, 0, 1, 0],]   # o

    y = [1, 2, 3, 4, 5]  # 희소 표현 대신 원-핫 인코딩 사용

    # 원-핫 인코딩
    y_one_hot = keras.utils.to_categorical(y, num_classes=6)

    model = keras.Sequential([
        keras.layers.Input(shape=(6,)),
        keras.layers.Dense(6, activation='softmax')
    ])

    model.compile(
        optimizer=keras.optimizers.Adam(0.1),
        loss=keras.losses.CategoricalCrossentropy(),
        metrics=['accuracy']
    )

    model.fit(x, y_one_hot, epochs=10, verbose=2)

    p = model.predict(x, verbose=0)
    p_arg = np.argmax(p, axis=1)

    # 정확도 계산
    print('acc:', np.mean(p_arg == y))


rnn_char_1_sparse()


ValueError: Failed to find data adapter that can handle input: (<class 'list'> containing values of types {'(<class \'list\'> containing values of types {"<class \'int\'>"})'}), <class 'numpy.ndarray'>

In [13]:
def rnn_char_1_sparse():
    x = [[1, 0, 0, 0, 0, 0],  # t
         [0, 1, 0, 0, 0, 0],  # e
         [0, 0, 1, 0, 0, 0],  # n
         [0, 0, 0, 1, 0, 0],  # s
         [0, 0, 0, 0, 1, 0]]  # o
    y = [1, 2, 3, 4, 5]       # e n s o r

    model = keras.Sequential([
         keras.layers.Input(shape=(6,)),
         keras.layers.Dense(6, activation='softmax')
    ])

    model.compile(optimizer=keras.optimizers.Adam(0.1),
                  loss=keras.losses.sparse_categorical_crossentropy,
                  metrics='acc')

    model.fit(x, y, epochs=10, verbose=2)

    p = model.predict(x, verbose=0)
    print(p)

    p_arg = np.argmax(p, axis=1)
    print('acc :', np.mean(p_arg == y))


# rnn_char_1_onehot()
rnn_char_1_sparse()

Epoch 1/10
1/1 - 0s - loss: 2.0493 - acc: 0.0000e+00
Epoch 2/10
1/1 - 0s - loss: 1.8396 - acc: 0.0000e+00
Epoch 3/10
1/1 - 0s - loss: 1.6435 - acc: 0.2000
Epoch 4/10
1/1 - 0s - loss: 1.4614 - acc: 0.6000
Epoch 5/10
1/1 - 0s - loss: 1.2929 - acc: 0.8000
Epoch 6/10
1/1 - 0s - loss: 1.1380 - acc: 0.8000
Epoch 7/10
1/1 - 0s - loss: 0.9967 - acc: 1.0000
Epoch 8/10
1/1 - 0s - loss: 0.8689 - acc: 1.0000
Epoch 9/10
1/1 - 0s - loss: 0.7543 - acc: 1.0000
Epoch 10/10
1/1 - 0s - loss: 0.6525 - acc: 1.0000
[[0.01607157 0.5552079  0.07936632 0.14298718 0.05618297 0.15018405]
 [0.04017738 0.09472466 0.6104007  0.07251836 0.11048049 0.07169858]
 [0.02769171 0.07718035 0.13994323 0.59357375 0.06503677 0.09657416]
 [0.02698952 0.11387533 0.12561125 0.07254168 0.58627236 0.07470994]
 [0.0283681  0.1326165  0.05734115 0.10962668 0.16372536 0.50832224]]
acc : 1.0
