In [4]:
import tensorflow.keras as keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

In [5]:
def rnn_char_2_sorted():
    # tensor -> enorst
    x = [[0, 0, 0, 0, 0, 1],  # t
         [1, 0, 0, 0, 0, 0],  # e
         [0, 1, 0, 0, 0, 0],  # n
         [0, 0, 0, 0, 1, 0],  # s
         [0, 0, 1, 0, 0, 0]]  # o

    y = [0, 1, 4, 2, 3]      # e n s o r

    model = keras.Sequential([
         keras.layers.Input(shape=(6,)),
         keras.layers.Dense(6, activation='softmax')
    ])

    model.compile(optimizer=keras.optimizers.Adam(0.1),
                  loss=keras.losses.sparse_categorical_crossentropy,
                  metrics='acc')

    model.fit(x, y, epochs=10, verbose=2)

    p = model.predict(x, verbose=0)
    print(p)

    p_arg = np.argmax(p, axis=1)
    print('acc :', np.mean(p_arg == y))


# rnn_char_1_onehot()
rnn_char_2_sorted()

Epoch 1/10
1/1 - 0s - loss: 1.6678 - acc: 0.0000e+00
Epoch 2/10
1/1 - 0s - loss: 1.4877 - acc: 0.4000
Epoch 3/10
1/1 - 0s - loss: 1.3205 - acc: 0.6000
Epoch 4/10
1/1 - 0s - loss: 1.1660 - acc: 1.0000
Epoch 5/10
1/1 - 0s - loss: 1.0243 - acc: 1.0000
Epoch 6/10
1/1 - 0s - loss: 0.8953 - acc: 1.0000
Epoch 7/10
1/1 - 0s - loss: 0.7790 - acc: 1.0000
Epoch 8/10
1/1 - 0s - loss: 0.6751 - acc: 1.0000
Epoch 9/10
1/1 - 0s - loss: 0.5832 - acc: 1.0000
Epoch 10/10
1/1 - 0s - loss: 0.5026 - acc: 1.0000
[[0.6869934  0.0587481  0.04131114 0.13377838 0.07015739 0.00901154]
 [0.05165514 0.6730919  0.07955303 0.05070564 0.13497725 0.01001708]
 [0.0860574  0.11048575 0.12526485 0.08665958 0.5735549  0.01797757]
 [0.04118085 0.04988469 0.67626715 0.07956792 0.14078164 0.01231766]
 [0.132688   0.07975891 0.05699396 0.6416707  0.07196808 0.01692038]]
acc : 1.0


In [26]:
def rnn_char_2_simple():
    # tensor -> enorst
    x = [[0, 0, 0, 0, 0, 1],  # t
         [1, 0, 0, 0, 0, 0],  # e
         [0, 1, 0, 0, 0, 0],  # n
         [0, 0, 0, 0, 1, 0],  # s
         [0, 0, 1, 0, 0, 0]]  # o
    y = [0, 1, 4, 2, 3]       # e n s o r

    x = [x]
    y = [y]

    vocab = sorted('tensor')
    vocab = np.array(vocab)     # ['e' 'n' 'o' 'r' 's' 't']

    model = keras.Sequential([
        keras.layers.Input(shape=(5, 6)),
        keras.layers.SimpleRNN(16, return_sequences=True),
        keras.layers.Dense(6, activation='softmax')
    ])

    model.compile(optimizer=keras.optimizers.Adam(0.1),
                  loss=keras.losses.sparse_categorical_crossentropy,
                  metrics='acc')

    model.fit(x, y, epochs=10, verbose=2)

    # 퀴즈
    # x, y를 3차원으로 변경했을 때의 에러를 수정하세요
    p = model.predict(x, verbose=0)
    print(p)

    p_arg = np.argmax(p, axis=2)
    print(p_arg)                # [[0 1 4 2 3]]

    print('acc :', np.mean(p_arg == y))

    # 퀴즈
    # 예측 결과를 디코딩하세요
    print([i for i in p_arg[0]])
    print([vocab[i] for i in p_arg[0]])
    print(vocab[p_arg[0]])
    print(vocab[p_arg])


# rnn_char_2_sorted()
rnn_char_2_simple()


NotImplementedError: Cannot convert a symbolic Tensor (simple_rnn_21/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported