n = 3 일 때 [ 1 2 3
             8  9 4
             7 6 5]
n = 4 일 떄 [1  2  3  4
            12 13 14 5
            11 16 15 6
            10 9  8  7]

출력

In [8]:
import numpy as np

n = 3
my_list = []
my_list = my_list(range(1, n**2))


TypeError: 'list' object is not callable

In [10]:
n = 3
my_list = []
for i in range(1, n**2):
    print(my_list)


[]
[]
[]
[]
[]
[]
[]
[]


In [12]:
n = 4
import numpy as np
result = np.zeros((n, n))
print(result)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
for i in range(4):
    result

In [14]:
n = 10
import numpy as np
result = np.zeros((n,n))
result

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
num = 1
i = 0
j = -1
trans_num = 1

while n > 0 :
# 열 증가
    for _ in range(n):
        j += trans_num
        result[i][j] = num
        num += 1
    n -= 1
    #행 증가
    for _ in range(n):
        i += trans_num
        result[i][j] = num
        num += 1
    trans_num *= -1
result

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  11.],
       [ 35.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  45.,  12.],
       [ 34.,  63.,  84.,  85.,  86.,  87.,  88.,  71.,  46.,  13.],
       [ 33.,  62.,  83.,  96.,  97.,  98.,  89.,  72.,  47.,  14.],
       [ 32.,  61.,  82.,  95., 100.,  99.,  90.,  73.,  48.,  15.],
       [ 31.,  60.,  81.,  94.,  93.,  92.,  91.,  74.,  49.,  16.],
       [ 30.,  59.,  80.,  79.,  78.,  77.,  76.,  75.,  50.,  17.],
       [ 29.,  58.,  57.,  56.,  55.,  54.,  53.,  52.,  51.,  18.],
       [ 28.,  27.,  26.,  25.,  24.,  23.,  22.,  21.,  20.,  19.]])